srun: error: task 0 launch failed: Slurmd could not execve job
srun: error: task 0 launch failed: Slurmd could not execve job
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1613, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_no_theta,  = self.mazeAgent.getMetrics(time=time)
ValueError: too many values to unpack (expected 6)
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1613, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_no_theta,  = self.mazeAgent.getMetrics(time=time)
ValueError: too many values to unpack (expected 6)
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1613, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_no_theta,  = self.mazeAgent.getMetrics(time=time)
ValueError: too many values to unpack (expected 6)
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1613, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_no_theta,  = self.mazeAgent.getMetrics(time=time)
ValueError: too many values to unpack (expected 6)
srun: error: enc2-node12: task 0: Exited with exit code 1
srun: error: enc2-node12: task 0: Exited with exit code 1
srun: error: enc2-node12: task 0: Exited with exit code 1
srun: error: enc2-node12: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1613, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_no_theta,  = self.mazeAgent.getMetrics(time=time)
ValueError: too many values to unpack (expected 6)
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1613, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_no_theta,  = self.mazeAgent.getMetrics(time=time)
ValueError: too many values to unpack (expected 6)
srun: error: enc2-node11: task 0: Exited with exit code 1
srun: error: enc2-node11: task 0: Exited with exit code 1
