srun: error: task 0 launch failed: Slurmd could not execve job
srun: error: task 0 launch failed: Slurmd could not execve job
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1643, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1643, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1643, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1643, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1643, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc2-node12: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1643, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc2-node12: task 0: Exited with exit code 1
srun: error: enc2-node12: task 0: Exited with exit code 1
srun: error: enc2-node12: task 0: Exited with exit code 1
srun: error: enc2-node11: task 0: Exited with exit code 1
srun: error: enc2-node11: task 0: Exited with exit code 1
